### ISSUE TITLE
Can't add more than 4 circles on date.

### ISSUE THREAD

**Issue by VjIntesols** [marcohc/roboto-calendar-view#28]
Using the property markCircleImage1(), markCircleImage2(), etc...

Can only go only up to 4 circles.

When adding the 5th one it gives Error inflating view.

Can any of you tried adding more than 4 circles?

**Comment by swapnil591** [comment]
How you added 3rd circle

**Comment by VjIntesols** [comment]
1) Search for markCircleImage1 in RobotoCalendarView.java file.
2) Create new function markCircleImage3 and repeat things done in markCircleImage1 with a different colour.

**Comment by swapnil591** [comment]
you mean add this module in your project or create a custom module from ref this module

**Comment by VjIntesols** [comment]
Yes exactly.
